- project:
    name: bstinsonmhk1-test2
    centos_ver: 7
    centos_arch: x86_64
    jobname: test2
    jobs:
        - ci.centos.org-rundotsh-job
    rundotshargs: 1 banana -q

- project:
    name: bstinsonmhk1-test3
    centos_ver: 6
    centos_arch: x86_64
    jobname: test3 
    jobs:
        - ci.centos.org-rundotsh-job
    rundotshargs: 42 orange -v --progress
